---
title: "PPE Empirical Coverage Under Competing Risks"
format:
  html:
    toc: true
    code-fold: true
execute:
  echo: false
  warning: false
  message: false
---

```{r setup}
library(tidyverse)
library(scales)

source("../plots/ecr_graph_function.R")
source("../plots/absolute_bias_graph_function.R")
source("../plots/bias_graph_function.R")
source("../plots/rmse_graph_function.R")
source("../plots/PPviz_parallel_function.R")

results_df <- read_csv("tables/final_results_complete.csv")
```

## Empirical Coverage

```{r fig-ecr-coverage, fig.width=9, fig.height=6, fig.cap="PPE empirical coverage under competing risks."}
plot_ecr(results_df)
```


## Absolute Bias

```{r fig-absolute-bias, fig.width=9, fig.height=6, fig.cap="PPE bias under competing risks."}
plot_absolute_bias(results_df)
```


## Bias

```{r fig-bias, fig.width=9, fig.height=6, fig.cap="PPE bias under competing risks."}
plot_bias(results_df)
```


## Root Mean Square Error

```{r fig-rmse, fig.width=9, fig.height=6, fig.cap="PPE root mean square error under competing risks."}
plot_rmse(results_df)
```


## Pohar-Perme Visualization by Lambda Scenario

## Pohar-Perme Visualization by Lambda Scenario

```{r fig-ppviz-all-lambdas, fig.width=9, fig.height=6, fig.cap="Pohar-Perme versus theoretical net survival by lambda scenario.", echo=FALSE}
#| layout-ncol: 1

plot_files <- sort(list.files("plots_data", pattern = "^ppviz_data_lambda_.*\\.rds$", full.names = TRUE))

for (p_file in plot_files) {
  p <- readRDS(p_file)
  
  plot(
    0, type = "n", xlim = c(0, max(p$t_seq_years)), ylim = c(0.9, 1.0),
    xlab = "Time since diagnosis (Years)", ylab = "Net Survival Probability",
    main = paste0("Net Survival: PP vs Theoretical\nLambda = ", sprintf("%.4f", p$lambda), 
                  "; Proportion of deaths due to cancer: ", p$pct_cancer, "%")
  )
  grid()
  
  # Plot individual sampled runs
  n_cols <- ncol(p$pp_surv_matrix)
  sampled_cols <- sample(seq_len(n_cols), size = min(20, n_cols))
  for (i in sampled_cols) {
    lines(p$t_seq_years, p$pp_surv_matrix[, i], col = rgb(0.2, 0.5, 0.8, alpha = 0.3), lwd = 1, type = "s")
  }
  
  # Plot mean and theoretical curves
  lines(p$t_seq_years, p$mean_pp_surv, col = "red", lwd = 3, type = "l")
  lines(p$t_seq_years, p$surv_theo_mean, col = "black", lwd = 3, lty = 2)
  
  legend("bottomleft",
    legend = c(paste0("Individual PP Estimates (N = ", length(sampled_cols), ")"),
               "Mean PP Estimate", "Theoretical Net Survival Curve S(t)"),
    col = c(rgb(0.2, 0.5, 0.8, alpha = 0.5), "red", "black"),
    lwd = c(2, 3, 3), lty = c(1, 1, 2), bty = "n", cex = 0.85
  )
}
```